### PR TITLE
Test schema classes

### PR DESCRIPTION
**Pull request by rmosolgo**
Oops, I didn't realize this branch had two commits, maybe only the second one is useful, to make sure that class-based schemas also work. I'll clean it up in a bit.

### CODE REVIEW

**Comment by rmosolgo** [comment]
The extra commit here puts all the `require`s in test_helper, then loads test helper in all tests. 

The upside here is that all tests have a shared entry point. I used this when I was hunting for #139 , it makes it a bit easier to hack on the test suite. 

The downside is that we lose one use case of the test suite: previously, you could run one file and it would run with only its specified `require`s. However, I think `rake test` didn't really use that, since it loaded _all_ test files anyway. 

Is anyone opposed to the `test_helper` refactor?

**Comment by josh** [comment]
> Is anyone opposed to the test_helper refactor?

Yes, can we please keep it as is.

**Comment by josh** [comment]
Do you mind if I cherry pick f92af49dec9a723f7dc9d80d1fad5fa80f03e4de into master? I think it makes sense to prefer the new schema classes when available. We can probably cut a new release soon that requires newer versions of graphql-ruby.

**Comment by rmosolgo** [comment]
Please do! Then feel free to close this, since that's the only needed part anyways, otherwise I'll try to clean this up when I get to some time.

**Comment by josh** [comment]
4a8f8f107f2e8757679d100823cb5a9724f2a4c1

**Pull request closed without merging**
