### PR TITLE
Add link to simple sinatra example app to readme

### PR DESCRIPTION
**Pull request by gauravtiwari**

### CODE REVIEW

**Comment by josh** [comment]
Neat.

I guess I have some feedback before considering linking to this example. I want to ensure any example linked up is following graphql-client best practices.

The main issue is that the queries don't live along side their usage.

https://github.com/gauravtiwari/graphql-sinatra-erb/blob/master/config/initializers/queries.rb

I realize that the ERB extension is mainly designed for Rails, but what if we made it work better for Sinatra?

**Comment by gauravtiwari** [comment]
@josh Sure! I thought about this too. Perhaps better if we make it work with any Tilt supported templating engine?  I am thinking to explore more into this in the weekend and make a PR.

**Comment by josh** [comment]
> Perhaps better if we make it work with any Tilt supported templating engine?

Ah, yeah, I'd be happy if this gem offered a `Tilt::ErubisTemplate` subclass that could be registered by Sinatra.

**Comment by emilebosch** [comment]
@josh any idea how we can scale this to other tilt templates too, we for instance use SLIM.

**Comment by josh** [comment]
> any idea how we can scale this to other tilt templates too, we for instance use SLIM.

I definitely think I could work in SLIM, but I don't think theres a magic solution for any given tilt engine. Each template engine is going to want to consider what definition syntax going to fit the best.

**Pull request closed without merging**
