### PR TITLE
Try the graphql-ruby 1.9.0 release candidate

### PR DESCRIPTION
**Pull request by rmosolgo**
I want to make sure that the new release won't break this gem.

### CODE REVIEW

**Comment by grcooper** [comment]
While upgrading one of our Apps using the GraphQL Client, I found that we were getting an odd error.
```
>> response
#<GraphQL::Client::Response:0x00007fa02e9a87f8 @original_hash={"data"=>{"node"=>{"id"=>"42"}}}, @data=#< node=...>, @errors=#<GraphQL::Client::Errors @messages={} @details={}>, @extensions=nil>
>> response.data
#< node=...>
>> response.data.to_json
"{\"data\":{\"node\":{\"id\":\"42\"}},\"casted_data\":{},\"errors\":[]}"
>> response.data.node
*** GraphQL::Client::InvariantError Exception: expected value to be one of (Shop), but was nil
nil
```
It seems like the error is coming from here: https://github.com/github/graphql-client/blob/9d6d7cb79760851b6edad14ba9b070a385672a19/lib/graphql/client/schema/possible_types.rb#L44

Is this an expected breaking change here?

**Comment by rmosolgo** [comment]
No, I don't expect a breakage in that case! I wonder why `casted_data` is empty in the snippet you posted, maybe it should have `"node" =>` in it?

**Comment by swalkinshaw** [comment]
This is a problem with our client layer on top, not graphql-client itself so don't worry about it 😄

**Comment by swalkinshaw** [comment]
Just to follow up, we do it a bit of manual work and call `insert_typename_fields` manually. We were relying on the document being mutated so the simple fix was to use the new returned document 🎉

**Comment by rmosolgo** [comment]
I don't plan on pushing this branch any further, glad it didn't break the build, anyway!

**Pull request closed without merging**
